-- FastRAG 业务流程管理（fastrag-bpm）种子数据
-- 适用日期：2026-09-02
-- 内容：1) bpm_node_type_meta 9 个 MVP 节点类型元数据（SSOT，前端画布节点库）
--      2) bpm_flow_template 5 个内置模板（设计文档 §14）
USE fastrag2;

-- ==================== 节点类型元数据（9 个 MVP 节点） ====================
INSERT INTO bpm_node_type_meta (type, label, icon, color, category, description, config_schema, default_config, enabled, sort_order) VALUES
('start',        '开始',      'VideoPlay',      '#67C23A', 'control', '标识业务流程的起始点', '[{"key":"inputParams","label":"输入参数(JSON)","type":"json","defaultValue":[]}]', '{"inputParams":[]}', 1, 10),
('end',          '结束',      'VideoPause',     '#F56C6C', 'control', '标识业务流程的终止点', '[{"key":"outputMapping","label":"输出映射(JSON)","type":"json","defaultValue":{}}]', '{"outputMapping":{}}', 1, 11),
('user_input',   '用户输入',  'EditPen',        '#E6A23C', 'input',   '在流程中获取用户输入信息', '[{"key":"fields","label":"输入字段(JSON)","type":"json","defaultValue":[]},{"key":"inputTimeoutMs","label":"输入超时(ms)","type":"number","defaultValue":86400000}]', '{"fields":[{"key":"input","label":"请输入","type":"text","required":true}],"inputTimeoutMs":86400000}', 1, 20),
('llm',          '大模型',    'MagicStick',     '#409EFF', 'execute', '调用大语言模型生成文本', '[{"key":"model","label":"模型","type":"select","options":["qwen2.5","deepseek-v3","gpt-4o"],"defaultValue":"qwen2.5"},{"key":"systemPrompt","label":"系统提示词","type":"textarea"},{"key":"userPrompt","label":"用户提示词模板","type":"textarea"},{"key":"temperature","label":"温度","type":"slider","min":0,"max":2,"step":0.1,"defaultValue":0.7},{"key":"maxTokens","label":"最大Tokens","type":"number","defaultValue":2048}]', '{"model":"qwen2.5","temperature":0.7,"maxTokens":2048}', 1, 30),
('kb_retrieval', '知识库检索', 'Collection',     '#E6A23C', 'execute', '检索知识库并返回 TopK 文档片段', '[{"key":"kbId","label":"知识库ID","type":"input"},{"key":"topK","label":"Top K","type":"number","min":1,"max":50,"defaultValue":5},{"key":"similarityThreshold","label":"相似度阈值","type":"slider","min":0,"max":1,"step":0.05,"defaultValue":0.5},{"key":"mode","label":"检索策略","type":"select","options":["vector","fulltext","hybrid"],"defaultValue":"hybrid"}]', '{"kbId":"","topK":5,"similarityThreshold":0.5,"mode":"hybrid"}', 1, 31),
('intent',       '意图识别',  'Aim',            '#9B59B6', 'execute', '对输入做意图分类', '[{"key":"model","label":"模型","type":"input","defaultValue":"qwen2.5"},{"key":"labels","label":"意图标签(JSON数组)","type":"json","defaultValue":[]},{"key":"confidenceThreshold","label":"置信度阈值","type":"slider","min":0,"max":1,"step":0.05,"defaultValue":0.8}]', '{"model":"qwen2.5","labels":[],"confidenceThreshold":0.8}', 1, 32),
('http',         'HTTP请求',  'Promotion',      '#FF6B6B', 'execute', '调用外部 HTTP 服务接口', '[{"key":"url","label":"请求URL","type":"input"},{"key":"method","label":"请求方法","type":"select","options":["GET","POST","PUT","DELETE"],"defaultValue":"GET"},{"key":"headers","label":"请求头(JSON)","type":"json","defaultValue":{}},{"key":"body","label":"请求体","type":"textarea"},{"key":"timeoutMs","label":"超时(ms)","type":"number","defaultValue":5000}]', '{"url":"","method":"GET","headers":{},"body":"","timeoutMs":5000}', 1, 33),
('condition',    '条件分支',  'Switch',         '#1ABC9C', 'control', '根据条件判断流程走向', '[{"key":"expression","label":"SpEL 条件表达式","type":"input","placeholder":"#vars['\''label'\'']=='\''通过'\''"}]', '{"expression":""}', 1, 40),
('subflow',      '子流程',    'Link',           '#00B4D8', 'execute', '将一个已有业务流程作为子流程嵌入', '[{"key":"subflowKey","label":"子流程(名称/ID)","type":"input"},{"key":"subflowVersionNo","label":"子流程版本号","type":"number"},{"key":"inputMapping","label":"输入映射(JSON)","type":"json","defaultValue":{}},{"key":"outputMapping","label":"输出映射(JSON)","type":"json","defaultValue":{}}]', '{"subflowKey":"","subflowVersionNo":null,"inputMapping":{},"outputMapping":{}}', 1, 34);

-- ==================== 内置模板（设计文档 §14，5 个） ====================
-- 1. 空白模板：start → end
INSERT INTO bpm_flow_template (id, name, category, description, canvas_data, is_builtin, thumbnail_url, created_by) VALUES
('bpmtpl_blank', '空白模板', 'blank', '从零开始搭建业务流程，仅含开始与结束节点',
'{"nodes":[{"nodeKey":"node_start","nodeType":"start","name":"开始","positionX":120,"positionY":180,"config":{"inputParams":[]}},{"nodeKey":"node_end","nodeType":"end","name":"结束","positionX":480,"positionY":180,"config":{"outputMapping":{}}}],"edges":[{"sourceNodeKey":"node_start","targetNodeKey":"node_end","edgeKind":"default","label":"","conditionExpr":"","priority":0}]}',
1, NULL, 'admin');

-- 2. RAG 检索问答：start → kb_retrieval → llm → end
INSERT INTO bpm_flow_template (id, name, category, description, canvas_data, is_builtin, thumbnail_url, created_by) VALUES
('bpmtpl_rag_qa', 'RAG 检索问答', 'rag', '用户输入问题 → 知识库混合检索 → 大模型生成回答',
'{"nodes":[{"nodeKey":"node_start","nodeType":"start","name":"开始","positionX":80,"positionY":200,"config":{"inputParams":[{"key":"query","label":"问题","type":"text","required":true}]}},{"nodeKey":"node_retrieval","nodeType":"kb_retrieval","name":"知识库检索","positionX":320,"positionY":200,"config":{"kbId":"","topK":5,"similarityThreshold":0.5,"mode":"hybrid"}},{"nodeKey":"node_llm","nodeType":"llm","name":"大模型回答","positionX":560,"positionY":200,"config":{"model":"qwen2.5","systemPrompt":"你是一个智能助手，请基于给定的知识库上下文回答问题。","userPrompt":"根据上下文: ${#vars['\''retrieval'\''].output.context}，回答: ${#vars['\''input'\''].query}","temperature":0.7,"maxTokens":2048}},{"nodeKey":"node_end","nodeType":"end","name":"结束","positionX":800,"positionY":200,"config":{"outputMapping":{"answer":"#vars['\''llm'\''].output.text"}}}],"edges":[{"sourceNodeKey":"node_start","targetNodeKey":"node_retrieval","edgeKind":"default","label":"","conditionExpr":"","priority":0},{"sourceNodeKey":"node_retrieval","targetNodeKey":"node_llm","edgeKind":"default","label":"","conditionExpr":"","priority":0},{"sourceNodeKey":"node_llm","targetNodeKey":"node_end","edgeKind":"default","label":"","conditionExpr":"","priority":0}]}',
1, NULL, 'admin');

-- 3. 多路召回 + 答案融合：start → kb_retrieval_A || kb_retrieval_B → llm 融合 → end
INSERT INTO bpm_flow_template (id, name, category, description, canvas_data, is_builtin, thumbnail_url, created_by) VALUES
('bpmtpl_multi_retrieval', '多路召回 + 答案融合', 'rag', '并行检索两个知识库，再由大模型融合生成统一答案',
'{"nodes":[{"nodeKey":"node_start","nodeType":"start","name":"开始","positionX":80,"positionY":240,"config":{"inputParams":[{"key":"query","label":"问题","type":"text","required":true}]}},{"nodeKey":"node_retrieval_a","nodeType":"kb_retrieval","name":"检索库A","positionX":320,"positionY":120,"config":{"kbId":"kb_a","topK":5,"similarityThreshold":0.5,"mode":"hybrid"}},{"nodeKey":"node_retrieval_b","nodeType":"kb_retrieval","name":"检索库B","positionX":320,"positionY":360,"config":{"kbId":"kb_b","topK":5,"similarityThreshold":0.5,"mode":"hybrid"}},{"nodeKey":"node_llm","nodeType":"llm","name":"答案融合","positionX":600,"positionY":240,"config":{"model":"qwen2.5","systemPrompt":"请融合多个知识源给出的答案，去重并给出统一回答。","userPrompt":"库A结果: ${#vars['\''retrieval_a'\''].output.context}，库B结果: ${#vars['\''retrieval_b'\''].output.context}，问题: ${#vars['\''input'\''].query}","temperature":0.7,"maxTokens":2048}},{"nodeKey":"node_end","nodeType":"end","name":"结束","positionX":840,"positionY":240,"config":{"outputMapping":{"answer":"#vars['\''llm'\''].output.text"}}}],"edges":[{"sourceNodeKey":"node_start","targetNodeKey":"node_retrieval_a","edgeKind":"default","label":"","conditionExpr":"","priority":0},{"sourceNodeKey":"node_start","targetNodeKey":"node_retrieval_b","edgeKind":"default","label":"","conditionExpr":"","priority":0},{"sourceNodeKey":"node_retrieval_a","targetNodeKey":"node_llm","edgeKind":"default","label":"","conditionExpr":"","priority":0},{"sourceNodeKey":"node_retrieval_b","targetNodeKey":"node_llm","edgeKind":"default","label":"","conditionExpr":"","priority":0},{"sourceNodeKey":"node_llm","targetNodeKey":"node_end","edgeKind":"default","label":"","conditionExpr":"","priority":0}]}',
1, NULL, 'admin');

-- 4. 意图识别 + 分支：start → intent → condition → (投诉→人工 / 其他→智能回复)
INSERT INTO bpm_flow_template (id, name, category, description, canvas_data, is_builtin, thumbnail_url, created_by) VALUES
('bpmtpl_intent_branch', '意图识别 + 分支', 'branch', '识别用户意图后按条件走向不同处理路径',
'{"nodes":[{"nodeKey":"node_start","nodeType":"start","name":"开始","positionX":60,"positionY":260,"config":{"inputParams":[{"key":"query","label":"问题","type":"text","required":true}]}},{"nodeKey":"node_intent","nodeType":"intent","name":"意图识别","positionX":300,"positionY":260,"config":{"model":"qwen2.5","labels":["投诉","咨询","其他"],"confidenceThreshold":0.8}},{"nodeKey":"node_condition","nodeType":"condition","name":"是否投诉","positionX":540,"positionY":260,"config":{"expression":"#vars['\''intent'\''].output.label=='\''投诉'\''"}},{"nodeKey":"node_llm_human","nodeType":"llm","name":"转人工坐席","positionX":760,"positionY":120,"config":{"model":"qwen2.5","systemPrompt":"生成转人工坐席的工单说明。","userPrompt":"${#vars['\''input'\''].query}","temperature":0.5,"maxTokens":1024}},{"nodeKey":"node_llm_bot","nodeType":"llm","name":"智能回复","positionX":760,"positionY":400,"config":{"model":"qwen2.5","systemPrompt":"你是智能客服，请简洁回答。","userPrompt":"${#vars['\''input'\''].query}","temperature":0.7,"maxTokens":2048}},{"nodeKey":"node_end_human","nodeType":"end","name":"结束-人工","positionX":960,"positionY":120,"config":{"outputMapping":{"result":"#vars['\''llm_human'\''].output.text"}}},{"nodeKey":"node_end_bot","nodeType":"end","name":"结束-智能","positionX":960,"positionY":400,"config":{"outputMapping":{"result":"#vars['\''llm_bot'\''].output.text"}}}],"edges":[{"sourceNodeKey":"node_start","targetNodeKey":"node_intent","edgeKind":"default","label":"","conditionExpr":"","priority":0},{"sourceNodeKey":"node_intent","targetNodeKey":"node_condition","edgeKind":"default","label":"","conditionExpr":"","priority":0},{"sourceNodeKey":"node_condition","targetNodeKey":"node_llm_human","edgeKind":"condition","label":"是","conditionExpr":"#vars['\''condition'\''].output.result==true","priority":1},{"sourceNodeKey":"node_condition","targetNodeKey":"node_llm_bot","edgeKind":"condition","label":"否","conditionExpr":"#vars['\''condition'\''].output.result==false","priority":2},{"sourceNodeKey":"node_llm_human","targetNodeKey":"node_end_human","edgeKind":"default","label":"","conditionExpr":"","priority":0},{"sourceNodeKey":"node_llm_bot","targetNodeKey":"node_end_bot","edgeKind":"default","label":"","conditionExpr":"","priority":0}]}',
1, NULL, 'admin');

-- 5. HTTP 集成：start → http → end
INSERT INTO bpm_flow_template (id, name, category, description, canvas_data, is_builtin, thumbnail_url, created_by) VALUES
('bpmtpl_http', 'HTTP 集成', 'integration', '通过 HTTP 请求调用外部服务并返回结果',
'{"nodes":[{"nodeKey":"node_start","nodeType":"start","name":"开始","positionX":100,"positionY":200,"config":{"inputParams":[{"key":"orderId","label":"订单ID","type":"text","required":true}]}},{"nodeKey":"node_http","nodeType":"http","name":"查询订单","positionX":360,"positionY":200,"config":{"url":"https://api.example.com/orders/${#vars['\''input'\''].orderId}","method":"GET","headers":{},"body":"","timeoutMs":5000}},{"nodeKey":"node_end","nodeType":"end","name":"结束","positionX":640,"positionY":200,"config":{"outputMapping":{"orderInfo":"#vars['\''http'\''].output.body"}}}],"edges":[{"sourceNodeKey":"node_start","targetNodeKey":"node_http","edgeKind":"default","label":"","conditionExpr":"","priority":0},{"sourceNodeKey":"node_http","targetNodeKey":"node_end","edgeKind":"default","label":"","conditionExpr":"","priority":0}]}',
1, NULL, 'admin');